/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eyal.kopelevich' at '1/1/18 10:41 AM' with Gradle 2.14.1
 *
 * @author eyal.kopelevich, @date 1/1/18 10:41 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
